services:
  - type: web
    name: collabcraft
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SEED_MOCK_DATA
        value: "false"
